<?php

namespace Cornichon\ForumBundle\Repository;

use Symfony\Component\Security\Core\User\UserInterface;

use Doctrine\ORM\EntityRepository;

/**
 * UserStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatRepository extends EntityRepository
{

    /**
     * Get a UserStat entity from a User
     * 
     * @param  UserInterface $user
     * 
     * @return UserStat|null
     */
    public function getByUser(UserInterface $user)
    {
        $queryBuilder = $this->createQueryBuilder('us')
                             ->select(array('us'))
                             ->where('us.user = :user_id')->setParameter('user_id', $user->getId());

        $query = $queryBuilder->getQuery();

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            return null;
        }
    }
}
